stages:
  - erstellung-csv
  - artifact-to-git

erstellung-csv:
  stage: erstellung-csv
  image: rocker/tidyverse:4.0.2
  script:
    - Rscript rfl-war.R
  artifacts:
    paths:
      - output.csv
  only:
    - main

artifact-to-git:
  stage: artifact-to-git
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add git
  script:
    - git config --global user.email "mail@jakob-eschler.de"
    - git config --global user.name "Jakob Eschler"
    - sh artifact-to-git.sh
  only:
    - main
