stages:
  - erstellung-csv
  - artifact-to-git

erstellung-csv:
  stage: erstellung-csv
  image: rocker/tidyverse:4.0.2
  script:
    - Rscript rfl-war.R
  artifacts:
    paths:
      - output.csv
  only:
    - main

artifact-to-git:
  stage: artifact-to-git
  image: curlimages/curl:latest
  script:
    - apk add git
    - sh artifact-to-git.sh
  only:
    - main
